# Config file for PhantomX Reactor

read_rate: 15
write_rate: 25
joints: {
    shoulder_yaw_joint: {id: 1, max_speed: 30.0, type: dynamixel},
    shoulder_pitch_joint: {id: 2, max_speed: 30.0, type: dynamixel},
    shoulder_pitch_mimic_joint: {id: 3, max_speed: 30.0, type: dynamixel},
    elbow_pitch_joint: {id: 5, max_speed: 30.0, type: dynamixel},
    elbow_pitch_mimic_joint: {id: 4, max_speed: 30.0, type: dynamixel},
    wrist_pitch_joint: {id: 6, max_speed: 30.0, invert: true, type: dynamixel},
    wrist_roll_joint: {id: 7, max_speed: 30.0, type: dynamixel},
    gripper_revolute_joint: {id: 8, max_speed: 40.0, range: 180, min_angle: -90.0, max_angle: 0, type: dynamixel},
}

controllers: {
    arm_controller: {type: follow_controller, joints: [shoulder_yaw_joint, shoulder_pitch_joint, shoulder_pitch_mimic_joint, elbow_pitch_joint, elbow_pitch_mimic_joint, wrist_pitch_joint, wrist_roll_joint, gripper_revolute_joint]},
}

#
# Be carefull with dependency of j2-j3 and j4-j5!!!
# Use the node phantomx_reactor_parallel_motor_joints.py for that purpose
